export interface ReviewData {
  id: string;
  paperTitle: string;
  venue: string;
  overallScore: number;
  confidence: number;
  summary: string;
  strengths: Array<{ point: string; detail: string }>;
  weaknesses: Array<{ point: string; detail: string }>;
  questions: string[];
  suggestions: string[];
}

/**
 * Export review as structured JSON.
 */
export function exportReviewAsJson(review: ReviewData): object {
  return {
    version: "1.0",
    exportedAt: new Date().toISOString(),
    review: {
      id: review.id,
      paper: review.paperTitle,
      venue: review.venue,
      scores: {
        overall: review.overallScore,
        confidence: review.confidence,
      },
      summary: review.summary,
      strengths: review.strengths,
      weaknesses: review.weaknesses,
      questions: review.questions,
      suggestions: review.suggestions,
    },
  };
}

/**
 * Export review as Markdown document.
 */
export function exportReviewAsMarkdown(review: ReviewData): string {
  const lines: string[] = [];

  lines.push(`# Review: ${review.paperTitle}`);
  lines.push("");
  lines.push(`**Venue:** ${review.venue}`);
  lines.push(`**Overall Score:** ${review.overallScore}/10`);
  lines.push(`**Confidence:** ${review.confidence}/5`);
  lines.push("");

  lines.push("## Summary");
  lines.push("");
  lines.push(review.summary || "_No summary provided._");
  lines.push("");

  lines.push("## Strengths");
  lines.push("");
  for (const s of review.strengths) {
    lines.push(`### ${s.point}`);
    lines.push(s.detail);
    lines.push("");
  }
  if (review.strengths.length === 0) {
    lines.push("_None identified._");
    lines.push("");
  }

  lines.push("## Weaknesses");
  lines.push("");
  for (const w of review.weaknesses) {
    lines.push(`### ${w.point}`);
    lines.push(w.detail);
    lines.push("");
  }
  if (review.weaknesses.length === 0) {
    lines.push("_None identified._");
    lines.push("");
  }

  lines.push("## Questions for Authors");
  lines.push("");
  for (const q of review.questions) {
    lines.push(`- ${q}`);
  }
  if (review.questions.length === 0) {
    lines.push("_No questions._");
  }
  lines.push("");

  lines.push("## Suggestions");
  lines.push("");
  for (const s of review.suggestions) {
    lines.push(`- ${s}`);
  }
  if (review.suggestions.length === 0) {
    lines.push("_No suggestions._");
  }
  lines.push("");

  lines.push("---");
  lines.push(`_Generated by OpenPaperReview on ${new Date().toISOString()}_`);

  return lines.join("\n");
}

/**
 * Export review as PDF.
 * Placeholder: generates a simple text-based PDF.
 * In production, use a proper PDF library (e.g., pdfkit, puppeteer).
 */
export async function exportReviewAsPdf(review: ReviewData): Promise<Buffer> {
  // Generate markdown first, then convert to a minimal PDF
  const markdown = exportReviewAsMarkdown(review);

  // Minimal PDF structure (placeholder - produces a text-only PDF)
  const content = markdown.replace(/[#*_\-]/g, "").trim();
  const pdfContent = [
    "%PDF-1.4",
    "1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj",
    "2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj",
    `3 0 obj<</Type/Page/Parent 2 0 R/MediaBox[0 0 612 792]/Contents 4 0 R/Resources<</Font<</F1 5 0 R>>>>>>endobj`,
    `5 0 obj<</Type/Font/Subtype/Type1/BaseFont/Helvetica>>endobj`,
    `4 0 obj<</Length ${content.length + 40}>>`,
    "stream",
    "BT /F1 10 Tf 50 750 Td",
    `(${content.substring(0, 500)}) Tj`,
    "ET",
    "endstream",
    "endobj",
    "xref",
    "0 6",
    "0000000000 65535 f ",
    "0000000009 00000 n ",
    "0000000058 00000 n ",
    "0000000115 00000 n ",
    "0000000266 00000 n ",
    "0000000206 00000 n ",
    "trailer<</Size 6/Root 1 0 R>>",
    "startxref",
    "0",
    "%%EOF",
  ].join("\n");

  return Buffer.from(pdfContent);
}
